# Generated by Django 4.2.1 on 2023-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='File',
            field=models.FileField(default='default.pdf', upload_to=''),
        ),
    ]
