# Generated by Django 4.2.1 on 2023-11-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avatar', '0002_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='File',
        ),
    ]
